services:
  - type: web
    name: CapstoneProject
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install --force-reinstall psycopg2-binary
      python manage.py collectstatic --no-input
    startCommand: |
      python manage.py migrate --noinput &&
      python manage.py createsuperuser --noinput || true &&
      gunicorn backend.wsgi:application
    autoDeploy: true

databases:
  - name: matchmentor-db
    databaseName: mentorship
    user: mentorship_user
