# Generated by Django 5.0.3 on 2025-07-02 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mentorship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
