# Generated by Django 5.0.3 on 2025-07-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mentorship_mentee_alter_mentorship_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='mentorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship', to='core.mentorship'),
        ),
    ]
