# Generated by Django 5.0.3 on 2025-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mentorshiprequest_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
