# Generated by Django 5.0.3 on 2025-07-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_session_date_alter_session_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mentorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.mentorship'),
        ),
    ]
