# Generated by Django 5.0.3 on 2025-07-05 17:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_session_mentorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.CharField(default=core.utils.cuid_wrapper, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='id',
            field=models.CharField(default=core.utils.cuid_wrapper, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=core.utils.cuid_wrapper, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=core.utils.cuid_wrapper, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
